Fix Unity 6 namespace error
Error:
Assets\RTLTMPro\Scripts\Editor\RTLTextMeshProEditor.cs(8,49): error CS0234: The type or namespace name 'TMP_UiEditorPanel' does not exist in the namespace 'TMPro.EditorUtilities' (are you missing an assembly reference?)